### PR TITLE
build on Windows

### LINKED ISSUE #1: CI (appveyor) fails, update configs
Some difficulty with building the code on [travis](https://travis-ci.org/Borda/pygco) and [appveyor](https://ci.appveyor.com/project/Borda/pygco), correct configuration needed

- travis
```
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/numpy-1.12.0.dist-info'
The command "pip install -r requirements.txt" failed and exited with 2 during .
```
- **appveyor**
```
make download
'make' is not recognized as an internal or external command, operable program or batch file.
Command exited with code 1
```

### PR DESCRIPTION
**Pull request by Borda**
resolves #1 

* build for Windows
* add appveyor CI [win]
* update configs

### CODE REVIEW

**Comment by Borda** [comment]
Windows build error:
```
C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:gco_source /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild /LIBPATH:C:\Python27\PC\VS9.0 /EXPORT:initlibcgco build\temp.win32-2.7\Release\gco_source\graph.obj build\temp.win32-2.7\Release\gco_source\maxflow.obj build\temp.win32-2.7\Release\gco_source\LinkedBlockList.obj build\temp.win32-2.7\Release\gco_source\GCoptimization.obj build\temp.win32-2.7\Release\gco\cgco.obj /OUT:build\lib.win32-2.7\gco\libcgco.pyd /IMPLIB:build\temp.win32-2.7\Release\gco_source\libcgco.lib /MANIFESTFILE:build\temp.win32-2.7\Release\gco_source\libcgco.pyd.manifest
LINK : error LNK2001: unresolved external symbol initlibcgco
build\temp.win32-2.7\Release\gco_source\libcgco.lib : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1120
```

**Comment by CaiWZ** [comment]
**E:\PythonProjects\SnowflakeRemoval\pyGCO-buil-win>python test_examples.py
Traceback (most recent call last):
  File "E:\PythonProjects\SnowflakeRemoval\pyGCO-buil-win\gco\__init__.py", line 8, in <module>
    from pygco import *
ModuleNotFoundError: No module named 'pygco'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PythonProjects\SnowflakeRemoval\pyGCO-buil-win\gco\pygco.py", line 5, in <module>
    from cgco import _cgco, _SMOOTH_COST_FN
ModuleNotFoundError: No module named 'cgco'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_examples.py", line 9, in <module>
    import gco
  File "E:\PythonProjects\SnowflakeRemoval\pyGCO-buil-win\gco\__init__.py", line 10, in <module>
    from gco.pygco import *
  File "E:\PythonProjects\SnowflakeRemoval\pyGCO-buil-win\gco\pygco.py", line 7, in <module>
    from .cgco import _cgco, _SMOOTH_COST_FN
  File "E:\PythonProjects\SnowflakeRemoval\pyGCO-buil-win\gco\cgco.py", line 47, in <module>
    _cgco = np.ctypeslib.load_library(_CGCO_LIB_NAME, _CGCO_LIB_PATH)
  File "D:\Program\Anaconda3\lib\site-packages\numpy\ctypeslib.py", line 152, in load_library
    return ctypes.cdll[libpath]
  File "D:\Program\Anaconda3\lib\ctypes\__init__.py", line 439, in __getitem__
    return getattr(self, name)
  File "D:\Program\Anaconda3\lib\ctypes\__init__.py", line 434, in __getattr__
    dll = self._dlltype(name)
  File "D:\Program\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
**
when i complied win，  the result of test_wrapper.cpp is right .but occured the problem when i test test_example.py.so how can i deal with it?

**Comment by CaiWZ** [comment]
LINK : error LNK2001: 无法解析的外部符号 PyInit_libcgco
i build on windows,but when i excute python setup.py install .The above problem occurs

**Comment by CaiWZ** [comment]
_init__.py
`try:
    from pygco import *
except:
    from gco.pygco import *`
in gco/pygco.py
`try:
    from cgco import _cgco, _SMOOTH_COST_FN
except Exception:
    from .cgco import _cgco, _SMOOTH_COST_FNs
`
i want to kown where can i get in "try" pycgo and cgco packge ,Thx

**Comment by CaiWZ** [comment]
Hi,when i build on windows,use python3.7,can you tell me  should i use python 3.6? Thx

**Comment by yig** [comment]
Add the following lines to `setup.py` to make it build on Windows. Inside `class BuildExt`, add:

    
    def get_export_symbols(self,ext):
        return None

**Comment by Borda** [comment]
seems to be failing for some numpy and float128 issue:
```
______________________ ERROR collecting gco/__init__.py _______________________
gco\__init__.py:10: in <module>
    from gco.pygco import *
gco\pygco.py:17: in <module>
    _float_types = [np.float, np.float32, np.float64, np.float128]
E   AttributeError: 'module' object has no attribute 'float128'
------------------------------- Captured stdout -------------------------------
found libs: ['libcgco.pyd']
```

**Comment by Borda** [comment]
@yig @CaiWZ thank you for your help and suggestions! =)
